version: "3.8"

services:
  infopoint-kiosk:
    container_name: infopoint_kiosk
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped

    ports:
      - "8081:80"

    environment:
      # Ustaw w Portainerze (Stack -> Environment variables):
      # API_KEY=...
      API_KEY: "${API_KEY}"

    networks:
      - kiosk-network

networks:
  kiosk-network:
    driver: bridge
